# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ff6a4b9d3b8468ea607c97457c0e0f824c6927980899c80e0f15e890e4f49c911c188a78e2fa448182365e33b2288f1f7b158acc4f01a8a20306f3782d6ec6c

test:
  secret_key_base: 47f30d47c7708c521fb7d9cfb4f81c13d052f74fbecf8464dab511ae02a93a441dc2b136e25551de213e9f5768d4c0c8ad912ab7b1b679bb595a0f8df2b0ef6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
